import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useSignInWithPopup, useSignInWithEmailAndPassword} from 'firebase-hook-v9';
export default function Home() {
  //const [ ] = useSignInWithEmailAndPassword()
  const {user, signInWithPopup, logOut} = useSignInWithPopup();
  const handlerSession = () => {
    if(user){
      logOut()
    }
    else{
      signInWithPopup()
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user && <pre>{JSON.stringify(user, null, 2)}</pre>}
      <main className={styles.main}>
      
         <button onClick={handlerSession}>{user? 'Logout' : 'Sign in with google'}</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
